apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  - experiment-crd.yaml
  - suggestion-crd.yaml
  - trial-crd.yaml
  - application.yaml
commonLabels:
  app.kubernetes.io/component: katib
  app.kubernetes.io/name: katib-crds
